# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
        {
                :hostname => "master1",
                :ip => "192.168.100.21",
                :box => "centos/6",
                :ram => 4096,
                :cpu => 1
        },
        {
                :hostname => "worker1",
                :ip => "192.168.100.22",
                :box => "centos/6",
                :ram => 4096,
                :cpu => 1
        },
        {
                :hostname => "worker2",
                :ip => "192.168.100.23",
                :box => "centos/6",
                :ram => 4096,                                                                                       
		:cpu => 1
        }
]

Vagrant.configure(2) do |config|
        servers.each do |machine|
                config.vm.define machine[:hostname] do |node|
                        node.vm.box = machine[:box]
                        node.vm.hostname = machine[:hostname]
                        node.vm.network "private_network", ip: machine[:ip]
                        node.vm.provider "virtualbox" do |vb|
                                vb.memory = machine[:ram]
                                vb.cpus = machine[:cpu]
                                vb.customize ["modifyvm", :id, "--nestedpaging", "off"]
                        end
                end
        end
end





