# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
        {
                :hostname => "hdpm1",
                :ip => "192.168.100.22",
                :box => "centos/6",
                :ram => 4096,
                :cpu => 1
        },
        {
                :hostname => "hdpw1",
                :ip => "192.168.100.23",
                :box => "centos/6",
                :ram => 4096,
                :cpu => 1
        },
        {
                :hostname => "hdpw2",
                :ip => "192.168.100.24",
                :box => "centos/6",
                :ram => 4096,
		:cpu => 1
        }
]

ssh_private_key = "#{Dir.home}/.ssh/id_rsa"
ssh_pub_key = "#{Dir.home}/.ssh/id_rsa.pub"

Vagrant.configure(2) do |config|

        servers.each do |machine|
                config.vm.define machine[:hostname] do |node|

			#copying the public and private keys to the guests
			node.vm.provision "file", source: "#{ssh_pub_key}", destination: "/tmp/authorized_keys"
		        node.vm.provision "file", source: "#{ssh_private_key}", destination: "/tmp/id_rsa"
			node.vm.provision "shell" do |s|
    				s.inline = <<-SHELL
					sudo mkdir -p /root/.ssh
					sudo chmod 700 /root/.ssh
					sudo mv /tmp/id_rsa /root/.ssh/
					sudo mv /tmp/authorized_keys /root/.ssh/
					sudo chmod 600 /root/.ssh/id_rsa
					sudo chmod 644 /root/.ssh/authorized_keys
					sudo chown root:root /root/.ssh/*
    				SHELL
			end

			#adding the hostname and ip address mapping in the hosts file
			node.vm.provision :hosts do |h|
				h.add_localhost_hostnames = false
                                servers.each do |n|
                                        h.add_host n[:ip], [n[:hostname]]
                                end
			end

                        node.vm.box = machine[:box]
                        node.vm.hostname = machine[:hostname]
                        node.vm.network "private_network", ip: machine[:ip]
                        node.vm.provider "virtualbox" do |vb|
                                vb.memory = machine[:ram]
                                vb.cpus = machine[:cpu]
                                vb.customize ["modifyvm", :id, "--nestedpaging", "off"]
				vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
                        end
                end
        end
end





